<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1zmzCDp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1zmzCDp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1zmzCDp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1zmzCDp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1zmzCDp\App_KernelDevDebugContainer([
    'container.build_hash' => '1zmzCDp',
    'container.build_id' => '85c54c29',
    'container.build_time' => 1641454814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1zmzCDp');
